// P&L attribution — turns the journal + telemetry into the pilot results, reproducibly.
//
// The results post's claims all reduce to four questions the raw data can answer:
//   1. Was it up?        heartbeats vs expected at the declared cadence
//   2. What did it do?   decision counts, with halts/errors first-class (not hidden)
//   3. What did it earn? portfolio change vs HODLing the starting inventory (IL-adjusted)
//   4. What did it see?  arb edge observed (detection) vs captured — the honest gap
//
// Pure functions over parsed records — no I/O here — so the numbers in the post can be
// regenerated by anyone from the journal excerpts + metrics file. The CLI does the reading.

export interface TickRecord {
  t: string;
  mode?: string;
  mid?: number;
  portfolioY?: number;
  lpValueY?: number;
  safe?: boolean;
  rebalance?: { action?: string; reason?: string };
  lpDecision?: { action?: string };
  action?: string; // present when something was broadcast (XYK), or the DLMM decision ("open"/"hold"/"recenter"/"skip")
  txid?: string;
  status?: string;
  arb?: { netEdgeY?: number; divergenceBps?: number };
  type?: string; // "tune" | "cycle-error" | "dlmm-recenter" | "dlmm-observe" | undefined (XYK tick)
  haltReasons?: string[];
  // dlmm-recenter/dlmm-observe entries (RecenterResult, spread into the journal line — see
  // agent-cli.ts's DLMM section): these are a SEPARATE type from the XYK tick above, so the
  // plain `ticks` census below never sees them without its own pass (see `dlmm` below).
  executed?: boolean;
  withdrawTxid?: string;
  addTxid?: string;
}

export interface MetricsSampleLite {
  t: string;
  mid: number;
  xBase: string;
  yBase: string;
  portfolioY: number;
  stxUsd?: number; // USD per STX at sample time — needed to reprice a HODL'd USDCx leg
}

// The LP and DLMM positions' underlying (x,y) quantities at the window's start sample —
// the same basis metrics.ts tracks for fees-net-IL. Only applied when its `t` matches the
// window's first sample (see buildReport): a mismatch means the basis was anchored
// elsewhere (e.g. a custom --since), where it would misrepresent the true start holdings.
export interface T0Basis {
  t: string;
  lpBasis?: { xQty: number; yQty: number };
  dlmmBasis?: { xQty: number; yQty: number };
  usdcxQty?: number;
}

export interface PnlReport {
  window: { from: string; to: string; hours: number };
  uptime: { beats: number; expected: number | null; pct: number | null };
  decisions: {
    ticks: number;
    holds: number;
    rebalances: number;
    lpAdds: number;
    lpWithdraws: number;
    dlmmOpens: number;
    dlmmRecenters: number;
    safetyHalts: number;
    cycleErrors: number;
    tunes: number;
  };
  txs: { broadcasts: number; successes: number; feesStx: number };
  pnl: {
    startY: number;
    endY: number;
    hodlEndY: number;
    totalPct: number; // portfolio change over the window
    vsHodlPct: number; // IL-adjusted: active portfolio vs HODLing start inventory
  } | null;
  arb: { opportunities: number; totalEdgeY: number; maxEdgeY: number };
}

const XD = 1e8; // sBTC base units
const YD = 1e6; // STX base units
const FEE_STX_PER_TX = 0.05;
const DLMM_FEE_STX_PER_TX = 0.3; // the deterministic FEE_USTX constant in dlmm-recenter-exec.ts

const inWindow = (t: string, from?: string, to?: string) =>
  (!from || t >= from) && (!to || t <= to);

export function buildReport(
  entries: TickRecord[],
  samples: MetricsSampleLite[],
  intervalSec: number,
  from?: string,
  to?: string,
  t0Basis?: T0Basis,
): PnlReport {
  const ticks = entries.filter((e) => !e.type && inWindow(e.t, from, to));
  const tunes = entries.filter((e) => e.type === "tune" && inWindow(e.t, from, to));
  const errors = entries.filter((e) => e.type === "cycle-error" && inWindow(e.t, from, to));
  // DLMM recenter/open decisions are a separate journal type (see TickRecord) — the plain
  // `ticks` filter above never sees them, so without this pass real, executed, on-chain DLMM
  // activity is invisible to the whole report (found 2026-09-19: a real recenter, two
  // confirmed transactions, showed up nowhere in this file's output).
  const dlmm = entries.filter((e) => e.type === "dlmm-recenter" && inWindow(e.t, from, to));
  const ss = samples.filter((s) => inWindow(s.t, from, to));

  const t0 = ss[0]?.t ?? ticks[0]?.t ?? "";
  const t1 = ss[ss.length - 1]?.t ?? ticks[ticks.length - 1]?.t ?? "";
  const hours = t0 && t1 ? Math.max(0, (Date.parse(t1) - Date.parse(t0)) / 3.6e6) : 0;

  // Uptime from heartbeats, exactly like the dashboard: honest "null" for ad-hoc runs.
  const expected =
    intervalSec > 0 && hours > 0 ? Math.floor((hours * 3600) / intervalSec) + 1 : null;
  const pct = expected ? Math.min(100, (ss.length / expected) * 100) : null;

  const act = (e: TickRecord) => e.rebalance?.action ?? "none";
  const decisions = {
    ticks: ticks.length,
    holds: ticks.filter((e) => act(e) === "none" && e.safe !== false).length,
    rebalances: ticks.filter((e) => (e.action ?? "").startsWith("swap") && e.status === "success").length,
    lpAdds: ticks.filter((e) => e.action === "add-liquidity" && e.status === "success").length,
    lpWithdraws: ticks.filter((e) => e.action === "withdraw-liquidity" && e.status === "success").length,
    dlmmOpens: dlmm.filter((e) => e.action === "open" && e.executed).length,
    dlmmRecenters: dlmm.filter((e) => e.action === "recenter" && e.executed).length,
    safetyHalts: ticks.filter((e) => e.safe === false).length,
    cycleErrors: errors.length,
    tunes: tunes.length,
  };

  const broadcasts = ticks.filter((e) => e.txid);
  const successes = broadcasts.filter((e) => e.status === "success");
  // DLMM broadcasts don't carry a per-txid on-chain status in the journal (no I/O here to go
  // fetch one — see the file header), so success is inferred conservatively from `executed`:
  // a completed "open" confirms 1 broadcast (the add), a completed "recenter" confirms 2 (the
  // withdraw + the re-add). An incomplete recenter still attempted a withdraw broadcast — that
  // counts toward `broadcasts` (an honest attempt happened) but never toward `successes` unless
  // `executed` says the whole sequence confirmed, which is the direction it's safe to err in.
  let dlmmBroadcasts = 0, dlmmSuccesses = 0;
  for (const e of dlmm) {
    const legs = (e.withdrawTxid ? 1 : 0) + (e.addTxid ? 1 : 0);
    dlmmBroadcasts += legs;
    if (e.executed) dlmmSuccesses += legs;
  }
  const txs = {
    broadcasts: broadcasts.length + dlmmBroadcasts,
    successes: successes.length + dlmmSuccesses,
    feesStx: +(broadcasts.length * FEE_STX_PER_TX + dlmmBroadcasts * DLMM_FEE_STX_PER_TX).toFixed(3),
  };

  // P&L vs HODL, from the telemetry (needs at least a start and an end sample).
  // Caveat by construction: only valid over a window with NO external capital changes.
  let pnl: PnlReport["pnl"] = null;
  if (ss.length >= 2) {
    const a = ss[0];
    const z = ss[ss.length - 1];
    // Free-wallet legs always count. LP/DLMM/USDCx legs held at window start are added
    // only when the basis was anchored at exactly this start sample — otherwise those
    // positions' start composition is unknown and must be left out rather than guessed.
    let hodlEndY = (Number(a.xBase) / XD) * z.mid + Number(a.yBase) / YD;
    if (t0Basis && t0Basis.t === a.t) {
      if (t0Basis.lpBasis) hodlEndY += t0Basis.lpBasis.xQty * z.mid + t0Basis.lpBasis.yQty;
      // dlmmBasis.yQty is USDCx (see metrics.ts: "y/USDCx in human units"), NOT y (STX) —
      // adding it directly here (as the code did until 2026-09-22) silently treated ~80
      // USDCx as ~80 STX, understating hodlEndY by roughly 1/stxUsd of that leg and inflating
      // vsHodlPct by several points. Fold it into the SAME USDCx→STX conversion as usdcxQty,
      // matching the dashboard's hodlNow() exactly.
      if (t0Basis.dlmmBasis) hodlEndY += t0Basis.dlmmBasis.xQty * z.mid;
      const usdcxQty = (t0Basis.usdcxQty ?? 0) + (t0Basis.dlmmBasis?.yQty ?? 0);
      if (usdcxQty > 0 && z.stxUsd) hodlEndY += usdcxQty / z.stxUsd;
    }
    pnl = {
      startY: +a.portfolioY.toFixed(2),
      endY: +z.portfolioY.toFixed(2),
      hodlEndY: +hodlEndY.toFixed(2),
      totalPct: +(((z.portfolioY - a.portfolioY) / a.portfolioY) * 100).toFixed(3),
      vsHodlPct: hodlEndY > 0 ? +(((z.portfolioY - hodlEndY) / hodlEndY) * 100).toFixed(3) : 0,
    };
  }

  const opps = ticks.filter((e) => e.arb && typeof e.arb.netEdgeY === "number");
  const arb = {
    opportunities: opps.length,
    totalEdgeY: +opps.reduce((s, e) => s + (e.arb!.netEdgeY ?? 0), 0).toFixed(2),
    maxEdgeY: +opps.reduce((m, e) => Math.max(m, e.arb!.netEdgeY ?? 0), 0).toFixed(2),
  };

  return { window: { from: t0, to: t1, hours: +hours.toFixed(1) }, uptime: { beats: ss.length, expected, pct: pct === null ? null : +pct.toFixed(1) }, decisions, txs, pnl, arb };
}

export function renderMarkdown(r: PnlReport): string {
  const pct = (v: number) => `${v >= 0 ? "+" : ""}${v}%`;
  const L: string[] = [];
  L.push(`## Pilot report — ${r.window.from} → ${r.window.to} (${r.window.hours}h)`);
  L.push("");
  L.push(`| Uptime | Ticks | Holds | Rebalances | LP add/wd | DLMM open/recenter | Halts | Errors |`);
  L.push(`|---|---|---|---|---|---|---|---|`);
  L.push(`| ${r.uptime.pct === null ? "n/a (ad-hoc)" : r.uptime.pct + "%"} (${r.uptime.beats}/${r.uptime.expected ?? "—"}) | ${r.decisions.ticks} | ${r.decisions.holds} | ${r.decisions.rebalances} | ${r.decisions.lpAdds}/${r.decisions.lpWithdraws} | ${r.decisions.dlmmOpens}/${r.decisions.dlmmRecenters} | ${r.decisions.safetyHalts} | ${r.decisions.cycleErrors} |`);
  L.push("");
  if (r.pnl) {
    L.push(`| Portfolio (STX) | vs HODL (IL-adj) | Total | Network fees paid |`);
    L.push(`|---|---|---|---|`);
    L.push(`| ${r.pnl.startY} → ${r.pnl.endY} | ${pct(r.pnl.vsHodlPct)} | ${pct(r.pnl.totalPct)} | ${r.txs.feesStx} STX (${r.txs.broadcasts} txs, ${r.txs.successes} ok) |`);
  } else {
    L.push(`_P&L: not enough telemetry samples in window._`);
  }
  L.push("");
  L.push(`Arb edge observed (detection only): **${r.arb.opportunities} opportunities, ${r.arb.totalEdgeY} STX total, best ${r.arb.maxEdgeY} STX** — measured, not captured; the LVR the pool leaks to arbitrageurs.`);
  return L.join("\n");
}
