// P&L attribution — turns the journal + telemetry into the pilot results, reproducibly.
//
// The results post's claims all reduce to four questions the raw data can answer:
//   1. Was it up?        heartbeats vs expected at the declared cadence
//   2. What did it do?   decision counts, with halts/errors first-class (not hidden)
//   3. What did it earn? portfolio change vs HODLing the starting inventory (IL-adjusted)
//   4. What did it see?  arb edge observed (detection) vs captured — the honest gap
//
// Pure functions over parsed records — no I/O here — so the numbers in the post can be
// regenerated by anyone from the journal excerpts + metrics file. The CLI does the reading.

export interface TickRecord {
  t: string;
  mode?: string;
  mid?: number;
  portfolioY?: number;
  lpValueY?: number;
  safe?: boolean;
  rebalance?: { action?: string; reason?: string };
  lpDecision?: { action?: string };
  action?: string; // present when something was broadcast
  txid?: string;
  status?: string;
  arb?: { netEdgeY?: number; divergenceBps?: number };
  type?: string; // "tune" | "cycle-error" | undefined (tick)
  haltReasons?: string[];
}

export interface MetricsSampleLite {
  t: string;
  mid: number;
  xBase: string;
  yBase: string;
  portfolioY: number;
}

export interface PnlReport {
  window: { from: string; to: string; hours: number };
  uptime: { beats: number; expected: number | null; pct: number | null };
  decisions: {
    ticks: number;
    holds: number;
    rebalances: number;
    lpAdds: number;
    lpWithdraws: number;
    safetyHalts: number;
    cycleErrors: number;
    tunes: number;
  };
  txs: { broadcasts: number; successes: number; feesStx: number };
  pnl: {
    startY: number;
    endY: number;
    hodlEndY: number;
    totalPct: number; // portfolio change over the window
    vsHodlPct: number; // IL-adjusted: active portfolio vs HODLing start inventory
  } | null;
  arb: { opportunities: number; totalEdgeY: number; maxEdgeY: number };
}

const XD = 1e8; // sBTC base units
const YD = 1e6; // STX base units
const FEE_STX_PER_TX = 0.05;

const inWindow = (t: string, from?: string, to?: string) =>
  (!from || t >= from) && (!to || t <= to);

export function buildReport(
  entries: TickRecord[],
  samples: MetricsSampleLite[],
  intervalSec: number,
  from?: string,
  to?: string,
): PnlReport {
  const ticks = entries.filter((e) => !e.type && inWindow(e.t, from, to));
  const tunes = entries.filter((e) => e.type === "tune" && inWindow(e.t, from, to));
  const errors = entries.filter((e) => e.type === "cycle-error" && inWindow(e.t, from, to));
  const ss = samples.filter((s) => inWindow(s.t, from, to));

  const t0 = ss[0]?.t ?? ticks[0]?.t ?? "";
  const t1 = ss[ss.length - 1]?.t ?? ticks[ticks.length - 1]?.t ?? "";
  const hours = t0 && t1 ? Math.max(0, (Date.parse(t1) - Date.parse(t0)) / 3.6e6) : 0;

  // Uptime from heartbeats, exactly like the dashboard: honest "null" for ad-hoc runs.
  const expected =
    intervalSec > 0 && hours > 0 ? Math.floor((hours * 3600) / intervalSec) + 1 : null;
  const pct = expected ? Math.min(100, (ss.length / expected) * 100) : null;

  const act = (e: TickRecord) => e.rebalance?.action ?? "none";
  const decisions = {
    ticks: ticks.length,
    holds: ticks.filter((e) => act(e) === "none" && e.safe !== false).length,
    rebalances: ticks.filter((e) => (e.action ?? "").startsWith("swap") && e.status === "success").length,
    lpAdds: ticks.filter((e) => e.action === "add-liquidity" && e.status === "success").length,
    lpWithdraws: ticks.filter((e) => e.action === "withdraw-liquidity" && e.status === "success").length,
    safetyHalts: ticks.filter((e) => e.safe === false).length,
    cycleErrors: errors.length,
    tunes: tunes.length,
  };

  const broadcasts = ticks.filter((e) => e.txid);
  const successes = broadcasts.filter((e) => e.status === "success");
  const txs = {
    broadcasts: broadcasts.length,
    successes: successes.length,
    feesStx: +(broadcasts.length * FEE_STX_PER_TX).toFixed(3),
  };

  // P&L vs HODL, from the telemetry (needs at least a start and an end sample).
  // Caveat by construction: only valid over a window with NO external capital changes.
  let pnl: PnlReport["pnl"] = null;
  if (ss.length >= 2) {
    const a = ss[0];
    const z = ss[ss.length - 1];
    const hodlEndY = (Number(a.xBase) / XD) * z.mid + Number(a.yBase) / YD;
    pnl = {
      startY: +a.portfolioY.toFixed(2),
      endY: +z.portfolioY.toFixed(2),
      hodlEndY: +hodlEndY.toFixed(2),
      totalPct: +(((z.portfolioY - a.portfolioY) / a.portfolioY) * 100).toFixed(3),
      vsHodlPct: hodlEndY > 0 ? +(((z.portfolioY - hodlEndY) / hodlEndY) * 100).toFixed(3) : 0,
    };
  }

  const opps = ticks.filter((e) => e.arb && typeof e.arb.netEdgeY === "number");
  const arb = {
    opportunities: opps.length,
    totalEdgeY: +opps.reduce((s, e) => s + (e.arb!.netEdgeY ?? 0), 0).toFixed(2),
    maxEdgeY: +opps.reduce((m, e) => Math.max(m, e.arb!.netEdgeY ?? 0), 0).toFixed(2),
  };

  return { window: { from: t0, to: t1, hours: +hours.toFixed(1) }, uptime: { beats: ss.length, expected, pct: pct === null ? null : +pct.toFixed(1) }, decisions, txs, pnl, arb };
}

export function renderMarkdown(r: PnlReport): string {
  const pct = (v: number) => `${v >= 0 ? "+" : ""}${v}%`;
  const L: string[] = [];
  L.push(`## Pilot report — ${r.window.from} → ${r.window.to} (${r.window.hours}h)`);
  L.push("");
  L.push(`| Uptime | Ticks | Holds | Rebalances | LP add/wd | Halts | Errors |`);
  L.push(`|---|---|---|---|---|---|---|`);
  L.push(`| ${r.uptime.pct === null ? "n/a (ad-hoc)" : r.uptime.pct + "%"} (${r.uptime.beats}/${r.uptime.expected ?? "—"}) | ${r.decisions.ticks} | ${r.decisions.holds} | ${r.decisions.rebalances} | ${r.decisions.lpAdds}/${r.decisions.lpWithdraws} | ${r.decisions.safetyHalts} | ${r.decisions.cycleErrors} |`);
  L.push("");
  if (r.pnl) {
    L.push(`| Portfolio (STX) | vs HODL (IL-adj) | Total | Network fees paid |`);
    L.push(`|---|---|---|---|`);
    L.push(`| ${r.pnl.startY} → ${r.pnl.endY} | ${pct(r.pnl.vsHodlPct)} | ${pct(r.pnl.totalPct)} | ${r.txs.feesStx} STX (${r.txs.broadcasts} txs, ${r.txs.successes} ok) |`);
  } else {
    L.push(`_P&L: not enough telemetry samples in window._`);
  }
  L.push("");
  L.push(`Arb edge observed (detection only): **${r.arb.opportunities} opportunities, ${r.arb.totalEdgeY} STX total, best ${r.arb.maxEdgeY} STX** — measured, not captured; the LVR the pool leaks to arbitrageurs.`);
  return L.join("\n");
}
